version: '3.4'
services:
  rasa:
    image: rasa/rasa:3.6.15-full  # Une version stable et complète
    container_name: rasa_it2
    ports:
      - "5005:5005"
    command:
      - run
      - --enable-api
      - --cors
      - "*"
